### PR TITLE
Implement tag page support

### LINKED ISSUE #31: Add tag page support
https://wordpress.org/support/topic/hashtag-insted-of-username
https://www.instagram.com/explore/tags/hike/

### LINKED ISSUE #48: Consider new filter for Instagram link
https://wordpress.org/support/topic/filter-for-link-class

### PR DESCRIPTION
**Pull request by scottsweb**
Closes #31 
Closes #48

### CODE REVIEW

**Comment by cfxd** [comment]
Great timing Scott, was about to begin a new project that needs this and was going to work on a PR along the lines of your suggestion but looks like you beat me to it. Will give this a try and let you know how it fares. Thank you! 👍

**Comment by scottsweb** [comment]
Not had any feedback but guessing all is well. Going to get this merged.

**Comment by cfxd** [comment]
Yes, all appears to work quite well, thank you!

**Comment by cfxd** [comment]
Heya Scott, this hasn't made its way into the plugin yet has it? Just wondering if/when it might? :)

**Pull request merged**
